name: 'Combine Pull Requests'
description: 'Combine multiple labelled pull requests by merging them on top of the current branch'
branding:
  icon: git-merge
  color: purple
inputs:
  label:
    description: 'The label to look for pull requests'
    required: false
    default: 'experiment'
  author-name:
    description: 'The author name of the merge commit'
    required: false
    default: 'nobody'
  author-email:
    description: 'The author email of the merge commit'
    required: false
    default: 'nobody@nobody'
  repo-token:
    description: 'The GitHub token'
    required: true
    default: 'experiment'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PULL_REQUEST_LABEL: ${{ inputs.label }}
    GITHUB_TOKEN: ${{ inputs.repo-token }}
    GIT_AUTHOR_NAME: ${{ inputs.author-name }}
    GIT_AUTHOR_EMAIL: ${{ inputs.author-email }}

